baseURL = 'https://Genshiken-zdxh.github.io/'
theme = ["github.com/D-Sketon/hugo-theme-reimu"]
title = "广州新华现代视觉文化研究社"

languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true